# This rule is not used by the project gsm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to secrets.pize.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gsm-operator
    app.kubernetes.io/managed-by: kustomize
  name: gsmsecret-viewer-role
rules:
- apiGroups:
  - secrets.pize.com
  resources:
  - gsmsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.pize.com
  resources:
  - gsmsecrets/status
  verbs:
  - get
