apiVersion: secrets.wayfair.com/v1alpha1
kind: GSMSecret
metadata:
  labels:
    app.kubernetes.io/name: gsm-operator
    app.kubernetes.io/managed-by: kustomize
  name: gsmsecret-sample
spec:
  # TODO(user): Add fields here
