apiVersion: v1
kind: Namespace
metadata:
  name: gsmsecret-test-ns
---
apiVersion: secrets.wayfair.com/v1alpha1
kind: GSMSecret
metadata:
  labels:
    app.kubernetes.io/name: gsm-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-gsm-secrets
  namespace: gsmsecret-test-ns
spec:
  targetSecret:
    name: my-secret             # name of K8s Secret
  gsmSecrets:
    - key: MY_ENVVAR
      projectId: "wf-gcp-prod"  # GSM Secret project ID
      secretId: my-secret       # GSM secret name
      version: "latest"         # recommend pinning a version for true “static”
